---

- name: Run cfg commands on routers
  hosts: 10.10.30.1
  gather_facts: false
  connection: local

  tasks:

    - name: Config ACL
      ios_config:
        before:
          - interface Ethernet 0/1
          - no ip access-group INET-to-LAN in
          - exit
          - no ip access-list extended INET-to-LAN
        parents:
          - ip access-list extended INET-to-LAN
        lines:
          - permit tcp 10.0.1.0 0.0.0.255 any eq www
          - permit tcp 10.0.1.0 0.0.0.255 any eq 22
          - permit icmp any any
        after:
          - interface Ethernet 0/1
          - ip access-group INET-to-LAN in
        match: exact
        provider: "{{ cli }}"
      register: result

    - name: Show commands
      debug: var=result.commands
      when: result.changed
